---

- hosts: IdealniServer

  vars:
    packages_add:
      - aptitude
      - docker-ce
      - fish
      - glances
      - ntp
      - ntpdate
      - python-certbot-nginx
    packages_repos:
      - repo: deb https://download.docker.com/linux/ubuntu xenial stable
        key: "https://download.docker.com/linux/ubuntu/gpg"
      - repo: deb http://ppa.launchpad.net/certbot/certbot/ubuntu xenial main
        key: "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7BF576066ADA65728FC7E70A8C47BE8E75BCA694"
  
  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
  
  post_tasks:
    - name: Set default shell and groups
      become: yes
      user:
        name: ondra
        shell: /usr/bin/fish
        groups: docker
        append: yes
    
    - name: Fish -- oh-my-fish -- install
      shell: curl -L http://get.oh-my.fish | fish /dev/stdin --noninteractive --yes
      args:
        creates: ~/.local/share/omf/init.fish
    
    - name: Bin directories -- present
      file:
        path: '~/.local/bin'
        state: directory
    
    - name: Bin directories -- in PATH
      lineinfile:
        line: 'set -g -x PATH {{ item }} $PATH'
        dest: ~/.config/fish/conf.d/path.fish
        create: yes
      with_items:
        - "$HOME/.local/bin"
    
    - name: Environment variables
      lineinfile:
        line: 'set -g -x {{ item.name }} {{ item.value }}'
        dest: ~/.config/fish/conf.d/variables.fish
        create: yes
      with_items:
        - { name: "EDITOR", value: "/usr/bin/vim" }
    
    - name: pure-ftpd -- force TLS
      become: yes
      copy:
        content: |
          3
        dest: /etc/pure-ftpd/conf/TLS
    
    - name: PHP -- config
      become: yes
      ini_file:
        dest: /etc/php/7.2/cli/php.ini
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: "PHP", option: "post_max_size", value: "16G" }
        - { section: "PHP", option: "upload_max_filesize", value: "16G" }
  
  roles:
    - name: zerotao.packages
      become: yes

